# Use postgres/example user/password credentials
version: '3.1'

services:

  mysql-local:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shortener
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306