spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:mysql://localhost:3306/shortener?allowPublicKeyRetrieval=true&useSSL=FALSE
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
